# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:51
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models
import saleor.product.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20160218_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='EUR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=saleor.product.models.fields.WeightField(decimal_places=2, max_digits=6, unit='kg', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True, verbose_name='price override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_override',
            field=saleor.product.models.fields.WeightField(blank=True, decimal_places=2, max_digits=6, null=True, unit='kg', verbose_name='weight override'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='EUR', decimal_places=2, max_digits=12, null=True, verbose_name='cost price'),
        ),
    ]
