# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shippingmethodcountry',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='country_code',
            field=models.CharField(blank=True, choices=[('', 'Any country'), ('SO', 'Somalia'), ('CM', 'Cameroon'), ('UG', 'Uganda'), ('NR', 'Nauru'), ('ML', 'Mali'), ('ME', 'Montenegro'), ('MH', 'Marshall Islands'), ('BG', 'Bulgaria'), ('FI', 'Finland'), ('FR', 'France'), ('SV', 'El Salvador'), ('GI', 'Gibraltar'), ('NO', 'Norway'), ('MO', 'Macao'), ('GQ', 'Equatorial Guinea'), ('BY', 'Belarus'), ('MN', 'Mongolia'), ('AD', 'Andorra'), ('DM', 'Dominica'), ('AI', 'Anguilla'), ('AO', 'Angola'), ('MQ', 'Martinique'), ('SK', 'Slovakia'), ('AR', 'Argentina'), ('CC', 'Cocos (Keeling) Islands'), ('NP', 'Nepal'), ('ZW', 'Zimbabwe'), ('TL', 'Timor-Leste'), ('TH', 'Thailand'), ('WF', 'Wallis and Futuna'), ('PN', 'Pitcairn'), ('CG', 'Congo'), ('CN', 'China'), ('KZ', 'Kazakhstan'), ('JM', 'Jamaica'), ('LK', 'Sri Lanka'), ('LV', 'Latvia'), ('MS', 'Montserrat'), ('EE', 'Estonia'), ('ER', 'Eritrea'), ('SY', 'Syrian Arab Republic'), ('KR', 'Korea (the Republic of)'), ('PF', 'French Polynesia'), ('VN', 'Viet Nam'), ('RW', 'Rwanda'), ('EG', 'Egypt'), ('BW', 'Botswana'), ('GU', 'Guam'), ('PG', 'Papua New Guinea'), ('PM', 'Saint Pierre and Miquelon'), ('BD', 'Bangladesh'), ('CR', 'Costa Rica'), ('TN', 'Tunisia'), ('EC', 'Ecuador'), ('ZM', 'Zambia'), ('SL', 'Sierra Leone'), ('PL', 'Poland'), ('KE', 'Kenya'), ('FM', 'Micronesia (Federated States of)'), ('BM', 'Bermuda'), ('IM', 'Isle of Man'), ('BO', 'Bolivia (Plurinational State of)'), ('IR', 'Iran (Islamic Republic of)'), ('TJ', 'Tajikistan'), ('GS', 'South Georgia and the South Sandwich Islands'), ('HU', 'Hungary'), ('MV', 'Maldives'), ('CK', 'Cook Islands'), ('SM', 'San Marino'), ('AX', 'Åland Islands'), ('IN', 'India'), ('SG', 'Singapore'), ('PY', 'Paraguay'), ('JO', 'Jordan'), ('NZ', 'New Zealand'), ('DZ', 'Algeria'), ('MD', 'Moldova (the Republic of)'), ('VA', 'Holy See'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('LS', 'Lesotho'), ('LA', "Lao People's Democratic Republic"), ('BV', 'Bouvet Island'), ('QA', 'Qatar'), ('KI', 'Kiribati'), ('LC', 'Saint Lucia'), ('OM', 'Oman'), ('GD', 'Grenada'), ('MX', 'Mexico'), ('HN', 'Honduras'), ('LY', 'Libya'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('IL', 'Israel'), ('MC', 'Monaco'), ('MW', 'Malawi'), ('GW', 'Guinea-Bissau'), ('NA', 'Namibia'), ('MK', 'Macedonia (the former Yugoslav Republic of)'), ('TG', 'Togo'), ('BL', 'Saint Barthélemy'), ('CA', 'Canada'), ('PA', 'Panama'), ('BR', 'Brazil'), ('JE', 'Jersey'), ('RU', 'Russian Federation'), ('FK', 'Falkland Islands  [Malvinas]'), ('TF', 'French Southern Territories'), ('YT', 'Mayotte'), ('DK', 'Denmark'), ('MA', 'Morocco'), ('CI', "Côte d'Ivoire"), ('NF', 'Norfolk Island'), ('MM', 'Myanmar'), ('LR', 'Liberia'), ('GN', 'Guinea'), ('IS', 'Iceland'), ('AZ', 'Azerbaijan'), ('KN', 'Saint Kitts and Nevis'), ('SJ', 'Svalbard and Jan Mayen'), ('KP', "Korea (the Democratic People's Republic of)"), ('IQ', 'Iraq'), ('PW', 'Palau'), ('PE', 'Peru'), ('RE', 'Réunion'), ('LI', 'Liechtenstein'), ('NL', 'Netherlands'), ('MT', 'Malta'), ('KY', 'Cayman Islands'), ('AF', 'Afghanistan'), ('MP', 'Northern Mariana Islands'), ('KW', 'Kuwait'), ('BF', 'Burkina Faso'), ('MR', 'Mauritania'), ('CH', 'Switzerland'), ('AW', 'Aruba'), ('LB', 'Lebanon'), ('JP', 'Japan'), ('CO', 'Colombia'), ('YE', 'Yemen'), ('GG', 'Guernsey'), ('TD', 'Chad'), ('NG', 'Nigeria'), ('TC', 'Turks and Caicos Islands'), ('CY', 'Cyprus'), ('CU', 'Cuba'), ('PT', 'Portugal'), ('SE', 'Sweden'), ('IE', 'Ireland'), ('PH', 'Philippines'), ('WS', 'Samoa'), ('BA', 'Bosnia and Herzegovina'), ('GE', 'Georgia'), ('AE', 'United Arab Emirates'), ('MG', 'Madagascar'), ('MU', 'Mauritius'), ('BH', 'Bahrain'), ('SS', 'South Sudan'), ('RS', 'Serbia'), ('BS', 'Bahamas'), ('BN', 'Brunei Darussalam'), ('SD', 'Sudan'), ('SA', 'Saudi Arabia'), ('GH', 'Ghana'), ('ES', 'Spain'), ('TW', 'Taiwan (Province of China)'), ('PR', 'Puerto Rico'), ('IO', 'British Indian Ocean Territory'), ('CX', 'Christmas Island'), ('DE', 'Germany'), ('ET', 'Ethiopia'), ('SZ', 'Swaziland'), ('GA', 'Gabon'), ('UY', 'Uruguay'), ('US', 'United States of America'), ('AT', 'Austria'), ('HT', 'Haiti'), ('TM', 'Turkmenistan'), ('SB', 'Solomon Islands'), ('GT', 'Guatemala'), ('HK', 'Hong Kong'), ('NU', 'Niue'), ('CL', 'Chile'), ('LT', 'Lithuania'), ('AQ', 'Antarctica'), ('VE', 'Venezuela (Bolivarian Republic of)'), ('GF', 'French Guiana'), ('AS', 'American Samoa'), ('UZ', 'Uzbekistan'), ('GB', 'United Kingdom of Great Britain and Northern Ireland'), ('AG', 'Antigua and Barbuda'), ('GM', 'Gambia'), ('SR', 'Suriname'), ('PK', 'Pakistan'), ('RO', 'Romania'), ('GR', 'Greece'), ('LU', 'Luxembourg'), ('HR', 'Croatia'), ('ZA', 'South Africa'), ('VI', 'Virgin Islands (U.S.)'), ('SN', 'Senegal'), ('FO', 'Faroe Islands'), ('CZ', 'Czech Republic'), ('MY', 'Malaysia'), ('VC', 'Saint Vincent and the Grenadines'), ('ST', 'Sao Tome and Principe'), ('UA', 'Ukraine'), ('GY', 'Guyana'), ('GP', 'Guadeloupe'), ('NC', 'New Caledonia'), ('ID', 'Indonesia'), ('BB', 'Barbados'), ('TV', 'Tuvalu'), ('BI', 'Burundi'), ('MZ', 'Mozambique'), ('SC', 'Seychelles'), ('CD', 'Congo (the Democratic Republic of the)'), ('FJ', 'Fiji'), ('BJ', 'Benin'), ('BZ', 'Belize'), ('DO', 'Dominican Republic'), ('SI', 'Slovenia'), ('TZ', 'Tanzania, United Republic of'), ('CW', 'Curaçao'), ('EH', 'Western Sahara'), ('GL', 'Greenland'), ('VU', 'Vanuatu'), ('VG', 'Virgin Islands (British)'), ('TO', 'Tonga'), ('NE', 'Niger'), ('HM', 'Heard Island and McDonald Islands'), ('TR', 'Turkey'), ('PS', 'Palestine, State of'), ('MF', 'Saint Martin (French part)'), ('KM', 'Comoros'), ('KG', 'Kyrgyzstan'), ('AU', 'Australia'), ('TK', 'Tokelau'), ('KH', 'Cambodia'), ('NI', 'Nicaragua'), ('AM', 'Armenia'), ('BT', 'Bhutan'), ('DJ', 'Djibouti'), ('UM', 'United States Minor Outlying Islands'), ('BE', 'Belgium'), ('AL', 'Albania'), ('CV', 'Cabo Verde'), ('SX', 'Sint Maarten (Dutch part)'), ('IT', 'Italy'), ('CF', 'Central African Republic'), ('TT', 'Trinidad and Tobago')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.PriceField(currency='EUR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
    ]
