branch-defaults:
  master:
    environment: lwc-DevEn-QNA1B5EG5LK7
global:
  application_name: lwc-ElasticBeanstalkApplication-6K32AGUH3KXF
  default_ec2_keyname: id_rsa
  default_platform: Python 3.4
  default_region: us-east-1
  profile: null
  sc: git
